### ISSUE TITLE
Error with AD Recycle Bin Enabled

### ISSUE THREAD

**Issue by IppSec** [trustedsec/DitExplorer#11]
I create the NTDS Backup with:
```
ntdsutil "activate instance ntds" "ifm" "create full C:\Windows\Temp\NTDS" quit quit
```
When I attempt to open the ntds.dit I get:
```
---------------------------
DIT Explorer
---------------------------
An error occurred while executing the command: Invalid API parameter

Invalid API parameter
---------------------------
OK   
---------------------------
```

Everything worked when I ran it on a domain controller without recycle bin, so I believe that is the issue. My main goal is to be able to extract the password of deleted users.

I am fairly certain the dit file is not corrupted as secretsdump does extract non-deleted users without issue.

**Comment by codewhisperer84** [comment]
What version of Windows is the DC running?

**Comment by IppSec** [comment]
Windows 2022.  Playbook i use to deploy it, only errors once the recycle bin task is ran.   https://github.com/synacktiv/ntdissector is able to extract all the recycle bin data, so I know the dump is valid

```
- name: Wait for Connection
  wait_for_connection:
    timeout: 120

- name: Freshen up the password as the domain would expire it
  win_shell: "net user {{ ansible_user }} {{ ansible_password }}"

- name: Install Active Directory Domain Services
  win_feature:
    name: AD-Domain-Services
    include_management_tools: yes
    include_sub_features: yes
    state: present
  register: result

- name: Running DCPromo
  win_domain:
    dns_domain_name: "{{ Domains.root.name }}"
    safe_mode_password: "{{ Domains.root.safe_mode_password}}"
    create_dns_delegation: no
    database_path: C:\Windows\NTDS
    sysvol_path: C:\Windows\SYSVOL
    domain_netbios_name: "{{ Domains.root.netbios_name }}"
  register: ad

- name: "Remove Defender"
  win_feature:
    name: Windows-Defender
    state: absent

- name: reboot server
  win_reboot:
    msg: "Configuring {{ Domains.root.name }} Rebooting..."
    reboot_timeout: 900
    test_command: 'Get-ADDomainController'
  when: ad.changed
  ignore_errors: yes
  async: 10
  poll: 0

- name: Disable automatic machine account password rotation
  ansible.windows.win_regedit:
    path: HKLM:\System\CurrentControlSet\Services\Netlogon\Parameters
    name: DisablePasswordChange
    type: dword
    data: 1
    state: present
  become: yes
  become_method: runas
  vars:
    ansible_become_user: SYSTEM

- name: "Enable AD Recycle Bin"
  win_shell: "Enable-ADOptionalFeature -Identity 'Recycle Bin Feature' -Scope ForestOrConfigurationSet -Target '{{ Domains.root.name }}' -Confirm:$false"
```
